### ISSUE TITLE
can't find the region_bbox.h5

### ISSUE THREAD

**Issue by State226** [bearcatt/LaBERT#13]
Thanks for your amazing job ,i download the dataset from Baidunetdisk you provided ,but when i run the code, in the line88 dataset.py, i cant find the region_bbox.h5, is it in the dataset you provide?

**Comment by State226** [comment]
I find it see #5

**Comment by Leng-bingo** [comment]
请问你的问题解决了么，我替换了bbox文件后出现如下错误，请问有解决吗
```
Traceback (most recent call last):
  File "E:/mycode/image_caption/LaBERT-master/train.py", line 202, in <module>
    arguments=arguments)
  File "E:/mycode/image_caption/LaBERT-master/train.py", line 44, in train
    for iteration, batch in enumerate(data_loader, start_iter):
  File "C:\Users\asus\.conda\envs\IC\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\asus\.conda\envs\IC\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\asus\.conda\envs\IC\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\asus\.conda\envs\IC\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\mycode\image_caption\LaBERT-master\dataset.py", line 95, in __getitem__
    return self.load_fn(index)
  File "E:\mycode\image_caption\LaBERT-master\dataset.py", line 125, in _get_item_train
    self.get_region_feature(sample.image_id)
  File "E:\mycode\image_caption\LaBERT-master\dataset.py", line 91, in get_region_feature
    region_spatial = torch.from_numpy(bboxes[name][:])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\asus\.conda\envs\IC\lib\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'COCO_val2014_000000140840' doesn't exist)"
```

**Comment by State226** [comment]
按照#5的将coco_detection_vg_thresh0.2_feat_gvd_checkpoint_trainvaltest.h5 改名为 region_bbox.h5
